In [13]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import random
import numpy as np
import socket, struct
import netaddr

import xxhash
%matplotlib inline

ModuleNotFoundError: No module named 'xxhash'

In [11]:
tp = pd.read_csv('capture20110818.pcap.netflow.labeled.csv', chunksize=1000)
df = pd.concat(tp, ignore_index=True)

# preprocessing
ips = df['SrcIPAddr:Port'].str.split(':')
df['SrcIPAddr'] = ips.str[0]
df['SrcIPPort'] = ips.str[-1]
ips = df['DstIPAddr:Port'].str.split(':')
df['DstIPAddr'] = ips.str[0]
df['DstIPPort'] = ips.str[-1]

df = df[df['SrcIPAddr']!='147.32.84.229']

most_freq = df.groupby(['SrcIPAddr'])['SrcIPAddr'].agg({'Frequency':'count'}).sort_values(['Frequency'], ascending=False).head(10)
most_freq_ips = list(zip(most_freq.index, np.reshape(most_freq.values, -1)))
print(most_freq_ips)

df.head()

MemoryError: 

In [ ]:
confidence_interval = 0.99
error_rate = 0.001
w = int(np.ceil(2/error_rate)) #amount of 'counters' within a hash function
d = int(np.ceil(-np.log(1-confidence_interval)/np.log(2))) #amount of hash functions

print(w, d)


def update_wd(_hash,loc):
    wd[_hash][loc] = wd[_hash][loc] + 1

In [3]:
wd = np.zeros((d, w))
#create the count min table
for i in range(d):
    #compute hashes of each source ip
    df['hash' + str(i)] = df['SrcIPAddr'].apply(lambda row: xxhash.xxh32(row, seed=i).intdigest())
    #update row in count min table for these hashes 
    df['hash' + str(i)].apply(lambda row: update_wd(i,row%w))
    
    
df.head()

NameError: name 'd' is not defined

In [6]:
print(wd)

[[3008. 2151.  206. ...  117.  173.  175.]
 [  79.   69.  996. ...  102.  276.   62.]
 [ 120.  263.   68. ...  158.   86.   96.]
 ...
 [ 135.   82.   66. ...   48. 2881.  127.]
 [ 142.  340.   95. ...  151. 7155.  250.]
 [  43.   65.  111. ...  293.  103.   83.]]


In [37]:
#for every unique ip calculate the hash row location and take the minimum value
df['freq'] = pd.Series(np.inf, index=df.index)

for i in range(d):
    df['freq'+str(i)] = df['hash'+str(i)].apply(lambda x: wd[i][x%w])
    df['freq'] = df[['freq','freq'+str(i)]].min(axis=1)

In [51]:
df = df.drop_duplicates('SrcIPAddr')
df[['SrcIPAddr','freq']].sort_values(['freq'], ascending=False).head()

SrcIPAddr      freq
24        147.32.84.229  179860.0
81          147.32.80.9  109348.0
2          147.32.84.59  101067.0
30        147.32.84.138   49471.0
9         147.32.84.118   12788.0
132        147.32.85.25   10453.0
20         147.32.80.13    9113.0
454770     147.32.84.95    8651.0
425        147.32.86.20    8329.0
257        147.32.85.26    7467.0
228       147.32.86.165    6513.0
1718      147.32.86.187    6494.0
210        147.32.85.34    6315.0
62        147.32.86.223    6069.0
487       147.32.84.111    5972.0
57         147.32.85.88    5878.0
317         147.32.85.8    5484.0
252        147.32.84.68    5008.0
4173      147.32.84.132    4723.0
756        147.32.85.30    3654.0
1724      147.32.84.170    3553.0
87         147.32.84.94    3548.0
37         147.32.86.53    3326.0
32         147.32.85.56    3297.0
5764      147.32.86.194    3064.0
192      74.125.232.215    2881.0
328       147.32.85.124    2848.0
62600      147.32.85.76    2799.0
411757    147.32.87.238    2699.0
154       89.221.217.12    2579.0
...                 ...       ...
412060      158.75.63.1     333.0
866      59.180.175.133     333.0
765       74.125.43.109     332.0
4278     195.113.232.90     331.0
928      213.180.35.166     330.0
3734       147.32.87.21     328.0
281         147.32.87.2     327.0
837     195.239.111.173     327.0
175630    147.32.85.112     325.0
5217       147.32.30.28     324.0
1924       147.32.85.36     324.0
27964    89.103.103.172     323.0
1097      209.85.148.19     323.0
1774       208.88.186.9     318.0
2401      80.239.149.27     317.0
2944     195.239.111.21     316.0
5138      147.122.45.75     314.0
5050        77.75.76.22     313.0
4507       147.32.86.75     311.0
1888      193.227.184.1     311.0
11080      147.32.85.75     311.0
3130     130.235.146.54     311.0
6664      147.32.84.186     311.0
2828        212.39.97.9     309.0
74219      94.98.143.64     307.0
422      195.113.235.89     307.0
5004     205.188.10.243     307.0
1052      66.249.66.250     307.0
237863     147.32.86.23     307.0
1848      81.191.93.173     306.0

[300 rows x 2 columns]

In [ ]:
def normalize(values):
    summed = sum([pair[1] for pair in values], 1)
    values = [(pair[0], pair[1]/summed) for pair in values]

    return values

def histogram(values):
    pos = np.arange(len(values))
    width = 0.8     # gives histogram aspect to the bar diagram

    ax = plt.axes()
    ax.set_xticks(pos + (width / 8))
    ax.set_xticklabels([pair[0] for pair in values])

    plt.bar(pos, [pair[1] for pair in values], width, color='r',  edgecolor = 'black')
    plt.xlabel('IP id')
    plt.ylabel('frequency')#normilized?
    plt.show()

In [8]:
def calc_error(truth, estimated):
    #generate ids for IPs
    ips = [pair[0] for pair in truth]
    e_ips = [pair[0] for pair in estimated]
    val_id = len(truth)
    truth_ids = []
    estimated_ids = []
    for i in range(len(truth)):
        truth_ids.append((i, truth[i][1]))
        if truth[i][0] not in e_ips:
            estimated_ids.append((i, 0))
        if estimated[i][0] in ips:
            estimated_ids.append((ips.index(truth[i][0]), estimated[i][1]))
        else:
            estimated_ids.append((val_id, estimated[i][1]))
            truth_ids.append((val_id, 0))
            val_id+=1
    truth_ids.sort(key=lambda tup: tup[0])
    estimated_ids.sort(key=lambda tup: tup[0])
    histogram(truth_ids)
    histogram(estimated_ids)
    
    ##normalize the dataset
    truth_ids = normalize(truth_ids)
    estimated_ids = normalize(estimated_ids)
        
    intersect_area = 0
    for i in range(len(truth_ids)):
        intersect_area += min(truth_ids[i][1], estimated_ids[i][1]) 
    print('Itersection area: ', intersect_area)

    

In [ ]:
most_freq_sketch_df = df[['SrcIPAddr','freq']].sort_values(['freq'], ascending=False).head(10)
most_freq_sketch = list(zip(np.reshape(most_freq_sketch_df['SrcIPAddr'].values, -1), np.reshape(most_freq_sketch_df['freq'].values, -1)))

calc_error(most_freq_ips, most_freq_sketch)