In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import random
import numpy as np
import socket, struct
import netaddr

import xxhash
%matplotlib inline

In [3]:
tp = pd.read_csv('capture20110818.pcap.netflow.labeled.csv', chunksize=1000)
df = pd.concat(tp, ignore_index=True)

# preprocessing
ips = df['SrcIPAddr:Port'].str.split(':')
df['SrcIPAddr'] = ips.str[0]
df['SrcIPPort'] = ips.str[-1]
ips = df['DstIPAddr:Port'].str.split(':')
df['DstIPAddr'] = ips.str[0]
df['DstIPPort'] = ips.str[-1]

df.head()

Date    Flow_start  Durat Prot        SrcIPAddr:Port tmp  \
0  2011-08-18  10:19:13.328  0.002  TCP   147.32.86.166:33426  ->   
1  2011-08-18  10:19:13.328  4.995  UDP     82.39.2.249:41915  ->   
2  2011-08-18  10:19:13.329  4.996  UDP    147.32.84.59:43087  ->   
3  2011-08-18  10:19:13.330  0.000  TCP   147.32.86.166:42020  ->   
4  2011-08-18  10:19:13.330  0.000  TCP  212.24.150.110:25443  ->   

         DstIPAddr:Port  Flags  Tos  Packets    Bytes  Flows       Label  \
0  212.24.150.110:25443  FRPA_    0        4      321      1  Background   
1    147.32.84.59:43087    INT    0      617    40095      1  Background   
2     82.39.2.249:41915    INT    0     1290  1909200      1  Background   
3     147.32.192.34:993     A_    0        1       66      1  Background   
4   147.32.86.166:33426   FPA_    0        2      169      1  Background   

   Labels       SrcIPAddr SrcIPPort       DstIPAddr DstIPPort  
0     NaN   147.32.86.166     33426  212.24.150.110     25443  
1     NaN     82.39.2.249     41915    147.32.84.59     43087  
2     NaN    147.32.84.59     43087     82.39.2.249     41915  
3     NaN   147.32.86.166     42020   147.32.192.34       993  
4     NaN  212.24.150.110     25443   147.32.86.166     33426

In [4]:
confidence_interval = 0.99
error_rate = 0.001
w = int(np.ceil(2/error_rate)) #amount of 'counters' within a hash function
d = int(np.ceil(-np.log(1-confidence_interval)/np.log(2))) #amount of hash functions

print(w, d)


def update_wd(_hash,loc):
    wd[_hash][loc] = wd[_hash][loc] + 1

2000 7


In [5]:
wd = np.zeros((d, w))
#create the count min table
for i in range(d):
    #compute hashes of each source ip
    df['hash' + str(i)] = df['SrcIPAddr'].apply(lambda row: xxhash.xxh32(row, seed=i).intdigest())
    #update row in count min table for these hashes 
    df['hash' + str(i)].apply(lambda row: update_wd(i,row%w))
    
    
df.head()

Date    Flow_start  Durat Prot        SrcIPAddr:Port tmp  \
0  2011-08-18  10:19:13.328  0.002  TCP   147.32.86.166:33426  ->   
1  2011-08-18  10:19:13.328  4.995  UDP     82.39.2.249:41915  ->   
2  2011-08-18  10:19:13.329  4.996  UDP    147.32.84.59:43087  ->   
3  2011-08-18  10:19:13.330  0.000  TCP   147.32.86.166:42020  ->   
4  2011-08-18  10:19:13.330  0.000  TCP  212.24.150.110:25443  ->   

         DstIPAddr:Port  Flags  Tos  Packets     ...      SrcIPPort  \
0  212.24.150.110:25443  FRPA_    0        4     ...          33426   
1    147.32.84.59:43087    INT    0      617     ...          41915   
2     82.39.2.249:41915    INT    0     1290     ...          43087   
3     147.32.192.34:993     A_    0        1     ...          42020   
4   147.32.86.166:33426   FPA_    0        2     ...          25443   

        DstIPAddr DstIPPort       hash0       hash1       hash2       hash3  \
0  212.24.150.110     25443  2505731307  2375472135  1602117669  1173467844   
1    147.32.84.59     43087   626978567  2169557788   523794326  4103352933   
2     82.39.2.249     41915  1115998567  1593929192   164951896  2222951432   
3   147.32.192.34       993  2505731307  2375472135  1602117669  1173467844   
4   147.32.86.166     33426  1720353717  4226395790  3408876200  3059175285   

        hash4       hash5       hash6  
0  3145439405  4051052248  3152582910  
1  3627694176  1210628020   629576023  
2  2722666753  2485698111   180318254  
3  3145439405  4051052248  3152582910  
4  3535919388  3910918517  2485411514  

[5 rows x 25 columns]

In [6]:
print(wd)

[[3008. 2151.  206. ...  117.  173.  175.]
 [  79.   69.  996. ...  102.  276.   62.]
 [ 120.  263.   68. ...  158.   86.   96.]
 ...
 [ 135.   82.   66. ...   48. 2881.  127.]
 [ 142.  340.   95. ...  151. 7155.  250.]
 [  43.   65.  111. ...  293.  103.   83.]]


In [37]:
#for every unique ip calculate the hash row location and take the minimum value
df['freq'] = pd.Series(np.inf, index=df.index)

for i in range(d):
    df['freq'+str(i)] = df['hash'+str(i)].apply(lambda x: wd[i][x%w])
    df['freq'] = df[['freq','freq'+str(i)]].min(axis=1)

In [51]:
df = df.drop_duplicates('SrcIPAddr')
df[['SrcIPAddr','freq']].sort_values(['freq'], ascending=False).head(300)

SrcIPAddr      freq
24        147.32.84.229  179860.0
81          147.32.80.9  109348.0
2          147.32.84.59  101067.0
30        147.32.84.138   49471.0
9         147.32.84.118   12788.0
132        147.32.85.25   10453.0
20         147.32.80.13    9113.0
454770     147.32.84.95    8651.0
425        147.32.86.20    8329.0
257        147.32.85.26    7467.0
228       147.32.86.165    6513.0
1718      147.32.86.187    6494.0
210        147.32.85.34    6315.0
62        147.32.86.223    6069.0
487       147.32.84.111    5972.0
57         147.32.85.88    5878.0
317         147.32.85.8    5484.0
252        147.32.84.68    5008.0
4173      147.32.84.132    4723.0
756        147.32.85.30    3654.0
1724      147.32.84.170    3553.0
87         147.32.84.94    3548.0
37         147.32.86.53    3326.0
32         147.32.85.56    3297.0
5764      147.32.86.194    3064.0
192      74.125.232.215    2881.0
328       147.32.85.124    2848.0
62600      147.32.85.76    2799.0
411757    147.32.87.238    2699.0
154       89.221.217.12    2579.0
...                 ...       ...
412060      158.75.63.1     333.0
866      59.180.175.133     333.0
765       74.125.43.109     332.0
4278     195.113.232.90     331.0
928      213.180.35.166     330.0
3734       147.32.87.21     328.0
281         147.32.87.2     327.0
837     195.239.111.173     327.0
175630    147.32.85.112     325.0
5217       147.32.30.28     324.0
1924       147.32.85.36     324.0
27964    89.103.103.172     323.0
1097      209.85.148.19     323.0
1774       208.88.186.9     318.0
2401      80.239.149.27     317.0
2944     195.239.111.21     316.0
5138      147.122.45.75     314.0
5050        77.75.76.22     313.0
4507       147.32.86.75     311.0
1888      193.227.184.1     311.0
11080      147.32.85.75     311.0
3130     130.235.146.54     311.0
6664      147.32.84.186     311.0
2828        212.39.97.9     309.0
74219      94.98.143.64     307.0
422      195.113.235.89     307.0
5004     205.188.10.243     307.0
1052      66.249.66.250     307.0
237863     147.32.86.23     307.0
1848      81.191.93.173     306.0

[300 rows x 2 columns]